name: ci

on:
  push:
    branches:
      - 'master'

env:
  IMAGE_NAME: "simaofsilva/noip-renewer"
  PYTHON_VERSION: "3.10.1"
  SELENIUM_VERSION: "4.1.0"

jobs:
  build-32:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2    
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/i386,linux/arm/v7,linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.PYTHON_VERSION }}-slim
            ${{ env.IMAGE_NAME }}:slim
          file: Dockerfile.32bits
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            SELENIUM_VERSION=${{ env.SELENIUM_VERSION }}
       
    
  build-64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action/issues/51#issuecomment-721279527
      -
        name: Checkout
        uses: actions/checkout@v2    
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.PYTHON_VERSION }}-alpine
            ${{ env.IMAGE_NAME }}:alpine
            ${{ env.IMAGE_NAME }}:latest
          file: Dockerfile
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            SELENIUM_VERSION=${{ env.SELENIUM_VERSION }}

