name: build and push image

on:
  push:
    branches:
      - 'master'
    paths:
      - Dockerfile*
      - .github/workflows/docker-build-and-push.yml
      - renew*.py

env:
  IMAGE_NAME: "simaofsilva/noip-renewer"
  SELENIUM_VERSION: "4.1.5" # renovate: datasource=pypi depName=selenium
  PIP_VERSION: "22.0.4" # renovate: datasource=pypi depName=pip

jobs:

  build-32:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Get commit short hash
        id: short_sha
        run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          platforms: linux/386,linux/arm/v7
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.short_sha.outputs.shortsha }}-debian
            ${{ env.IMAGE_NAME }}:debian
          file: Dockerfile.32bits
          build-args: PIP_VERSION=${{ env.PIP_VERSION }}

  build-64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Get commit short hash
        id: short_sha
        run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.short_sha.outputs.shortsha }}-alpine
            ${{ env.IMAGE_NAME }}:alpine
            ${{ env.IMAGE_NAME }}:latest
          file: Dockerfile
          build-args: |
            SELENIUM_VERSION=${{ env.SELENIUM_VERSION }}
            PIP_VERSION=${{ env.PIP_VERSION }}

  delete_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 15
          keep_minimum_runs: 5
